### ISSUE TITLE
Update MediaItem

### ISSUE THREAD

**Issue by egoan82** [yagoliveira92/radio-basic#1]
Good day,

First to thank you because your contribution has helped me a lot, I want to ask you how you can update the mediaItem from the hompage with the getMetadata function.

I want to get the information in the notification bar updated when getMetadata information is updated.

Object that I want to update from getMetadata:

MediaItem mediaItem = MediaItem (
       id: 'audio_1',
       album: 'ABC Radio',
       title: 'A radio que não never tires vc');

I appreciate your kind cooperation.

**Comment by yagoliveira92** [comment]
I'm so sorry for too late answer. I will change the app for using Mobx in next weeks, in this Update I'm expected to upgrade this feature.
